#!/bin/bash
set -euo pipefail

HYPR_CONF="$HOME/.config/hypr/hyprland.conf"
BASH_PROF="$HOME/.bash_profile"
SHELL_ACTUAL=$(basename "$SHELL")
LINEA='if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
	exec start-hyprland
fi'


# Detectar Shell actual
if [ "$SHELL_ACTUAL" = "zsh" ]; then
	BASH_PROF="$HOME/.zprofile"
elif [ "$SHELL_ACTUAL" = "bash" ]; then
	BASH_PROF="$HOME/.bash_profile"
else
	error "Shell no soportado: $SHELL_ACTUAL"
fi

# --- COLORES ---
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()   { echo -e "${GREEN}[+]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[x]${NC} $1"; exit 1; }

# --- FUNCIONES ---
actualizar_sistema(){
	log "Actualizando sistema..."
	sudo pacman -Syu --noconfirm
}

instalar_base(){
	log "Instalando herramientas base..."
	sudo pacman -S --noconfirm --needed \
		base-devel git curl wget nvim zsh htop tmux
}

instalar_aur(){
	command -v yay &>/dev/null || {
		git clone https://aur.archlinux.org/yay.git /tmp/yay
		cd /tmp/yay && makepkg -si --noconfirm && cd -&& rm -rf /tmp/yay
	}
	yay -S --noconfirm google-chrome
}

configurar_zsh(){
	log "Configurando zsh..."
	chsh -s $(which zsh)
	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
}

instalar_hyprland(){
	sudo pacman -S hyprland kitty

	# Reemplazar la linea en .bash_profile
	log "Ubicando bash_profile..."
	echo $BASH_PROF

	# Crear .bash_profile si no existe
	if [ ! -f "$BASH_PROF" ]; then
		touch "BASH_PROF"
		log ".bash_profile creado"
	fi

	# Agregar solo si no existe ya
	if ! grep -q "start-hyprland" "$BASH_PROF"; then
		echo "$LINEA" >> "$BASH_PROF"
		log "Hyprland agregado al inicio"
	else
		warn "Ya existe la configuracion"
	fi

}

configuracion_hyprland(){
	log "Ubicando Archivo de configuracion..."
	echo $HYPR_CONF
	log "Respaldando Configuracion Anterior..."
	cp "$HYPR_CONF" "$HYPR_CONF.bak"
	log "Respaldo Completado..."

	# Comentar la linea autogenerated
	if grep -q "^autogenerated" "$HYPR_CONF"; then
		sed -i 's/^autogenerated/# autogenerated/' "$HYPR_CONF"
		log "Linea autogenerated comentada"
	else
		warn "La linea ya esta comentada o no existe..." 
	fi

	# Instalar HyprPaper
	yay -S hyprpaper

	# Recargar HyprLand
	# hyprctl reload
}

# --- MENU PRINCIPAL --
main(){
	echo "==========================="
	echo "   INSTALADOR ARCH LINUX   "
	echo "==========================="
	echo "1) Actualizar sistema"
	echo "2) Instalar paquetes base"
	echo "3) Instalar paquetes AUR"
	echo "4) Configurar zsh + Oh My Zsh"
	echo "5) Todo lo anterior"
	echo "6) Instalar HyprLand"
	echo "7) Configurar HyprLand"
	echo "0) Salir"
	echo ""
	read -rp "Elige una opcion: " opcion

	case $opcion in
		1) actualizar_sistema;;
		2) instalar_base ;;
		3) instalar_aur ;;
		4) configurar_zsh ;;
		5) actualizar_sistema; instalar_base; instalar_aur;;
		6) instalar_hyprland;;
		7) configuracion_hyprland;;
		0) exit 0;;
		*) error "Opccion invalida"
	esac

	log "Instalacion Completada!!!..."
}

	main
